import createClient from '@sanity/client';

const client = createClient({
  projectId: 'dg157s6c', 
  dataset: 'production',
  useCdn: false,
  apiVersion: '2023-01-01',
  token: 'skv5ejQyc8EBAKfWucmc1aPnBmNpTqLXBLnp6DkHaMCn2WKOpLD8rwTLUqZr8XHxHVz9WeVCZoavDqjt6Xv9kU3MGlGitimpEoZIzmJVXcuYrF4gleK3RmbUUIQphwwXPZ0BG6amCKuC5oToaOFPbiAEHXPKds0LwMrPyDzcjg5wwO1g3Bf9', 
});

const mentors = [
  {
    _type: 'mentor',
    name: 'Szalszabilla Rahayu, S.Farm., M.Farm',
    slug: { _type: 'slug', current: 'szalszabilla-rahayu' },
    role: 'Pharmaceutical Cosmetic Sciences',
    rating: 5,
    reviews: '150+',
    cardColor: 'bg-brand-pink',
    borderColor: 'border-white',
    expertise: ['Cosmetic Formulation', 'R&D', 'Pharmapreneur'],
    bio: 'Founder & CEO Teman Farmasi | 30+ active speakers in webinars, podcast, guest lectures | Best Oral Presentation Seminar Nasional "Pengembangan Obat Berbasis Herbal" | R&D Cosmetics Formulation Certificate & Completed Score: 90/100',
    featured: true,
    order: 1,
  },
  {
    _type: 'mentor',
    name: 'apt. Camelia Ayu Prawesti, M.Farm',
    slug: { _type: 'slug', current: 'camelia-ayu-prawesti' },
    role: 'Pharmaceutical Cosmetic Sciences',
    rating: 5,
    reviews: '120+',
    cardColor: 'bg-brand-blue',
    borderColor: 'border-white',
    expertise: ['Cosmetic Sciences', 'Research', 'International Programs'],
    bio: '1st Winner of National Essay Competition APTFMA | Delegation of Student Exchange Program in Egypt | 2nd Winner of Outstanding Student Faculty of Pharmacy',
    featured: true,
    order: 2,
  },
  {
    _type: 'mentor',
    name: 'Khansa Fitrah Shaliha, S.Farm., M.Farm',
    slug: { _type: 'slug', current: 'khansa-fitrah-shaliha' },
    role: 'Pharmaceutical Cosmetic Sciences',
    rating: 5,
    reviews: '100+',
    cardColor: 'bg-brand-yellow',
    borderColor: 'border-white',
    expertise: ['Cosmetic Sciences', 'Public Education', 'Chemistry'],
    bio: 'Lulusan terbaik Program Sarjana dan Magister Farmasi dengan predikat Cumlaude | Pemateri PKM mengenai "Cerdas Memilih dan Menggunakan Kosmetik yang Aman" | ONMIPA-PT 2022 Bidang Kimia',
    featured: true,
    order: 3,
  },
  {
    _type: 'mentor',
    name: 'apt. Mutiara Ariani Saputri, S.Farm',
    slug: { _type: 'slug', current: 'mutiara-ariani-saputri' },
    role: 'Natural Products & Microbiology',
    rating: 5,
    reviews: '95+',
    cardColor: 'bg-brand-purple',
    borderColor: 'border-white',
    expertise: ['Natural Products', 'Microbiology', 'International Research'],
    bio: 'Lulusan terbaik Program Sarjana Farmasi dan Profesi Apoteker dengan predikat Cumlaude | Delegasi "Internasional Summer School Program" (APTFI) | Delegasi "2nd Internasional Summer School Program" (APTFI)',
    featured: true,
    order: 4,
  },
  {
    _type: 'mentor',
    name: 'Fitri Melati, S.Farm., M.Farm',
    slug: { _type: 'slug', current: 'fitri-melati' },
    role: 'Natural Products & Pharmacology',
    rating: 5,
    reviews: '80+',
    cardColor: 'bg-brand-teal',
    borderColor: 'border-white',
    expertise: ['Natural Products', 'Pharmacology'],
    bio: 'Spesialis Farmasi Bahan Alam dan Farmakologi dengan pengalaman riset dan pengajaran yang mendalam',
    featured: false,
    order: 5,
  },
  {
    _type: 'mentor',
    name: 'apt. Salsabila Putri, S.Farm',
    slug: { _type: 'slug', current: 'salsabila-putri' },
    role: 'Pharmaceutical Cosmetic Sciences',
    rating: 5,
    reviews: '110+',
    cardColor: 'bg-brand-pink',
    borderColor: 'border-white',
    expertise: ['Cosmetic Sciences', 'International Research', 'Competency Mentoring'],
    bio: 'Delegation of Student Exchange MSU Malaysia | Participants International Research Conference on Pharmaceuticals & Allied Science (IRCAPAS 2.0) Malaysia | Mentor Pendampingan Uji Kompetensi Mahasiswa Program Profesi Apoteker Indonesia',
    featured: true,
    order: 6,
  },
  {
    _type: 'mentor',
    name: 'Muhammad Aqsyal, S.Farm., M.Farm',
    slug: { _type: 'slug', current: 'muhammad-aqsyal' },
    role: 'Pharmaceutical Cosmetic Sciences',
    rating: 5,
    reviews: '90+',
    cardColor: 'bg-brand-blue',
    borderColor: 'border-white',
    expertise: ['Cosmetic Sciences', 'Academic Excellence'],
    bio: 'Beasiswa penuh pendidikan | Mahasiswa Prestasi 2019/2020 Universitas Gunadarma Program Studi Farmasi | Narasumber dalam DIES NATALIS 2025 "Pharmation 8.0: Generasi Baru, Langkah Baru, Tujuan yang Satu"',
    featured: false,
    order: 7,
  },
  {
    _type: 'mentor',
    name: 'apt. Hesti Ratnasari, S.Farm',
    slug: { _type: 'slug', current: 'hesti-ratnasari' },
    role: 'Clinical and Community Pharmaceutical',
    rating: 5,
    reviews: '105+',
    cardColor: 'bg-brand-yellow',
    borderColor: 'border-white',
    expertise: ['Clinical Pharmacy', 'Community Pharmacy', 'Research Funding'],
    bio: 'Lulusan terbaik Program Sarjana Farmasi dengan predikat Cumlaude | Lolos Pendanaan Dikti tingkat Nasional PKM: "Ekstrak Bunga Rosella sebagai Anti Hiperkolesterol" | Lolos Pendanaan Dikti PKM: "Formulasi Nutraseutikal Coklat dan Daun Katuk sebagai ASI Booster"',
    featured: true,
    order: 8,
  },
  {
    _type: 'mentor',
    name: 'Vina Agustin, S.Farm., M.Farm',
    slug: { _type: 'slug', current: 'vina-agustin' },
    role: 'Natural Products & Pharmacology',
    rating: 5,
    reviews: '75+',
    cardColor: 'bg-brand-purple',
    borderColor: 'border-white',
    expertise: ['Natural Products', 'Pharmacology'],
    bio: 'Spesialis dalam Farmasi Bahan Alam dan Farmakologi dengan dedikasi tinggi dalam riset dan pendampingan mahasiswa',
    featured: false,
    order: 9,
  },
  {
    _type: 'mentor',
    name: 'Khoiron Basulloh, S.Farm., M.M., M.Biomed. (AAM)',
    slug: { _type: 'slug', current: 'khoiron-basulloh' },
    role: 'Pharmaceutical Cosmetic Sciences',
    rating: 5,
    reviews: '200+',
    cardColor: 'bg-brand-teal',
    borderColor: 'border-white',
    expertise: ['Pharmacodermatology', 'Aesthetic Medicine', 'Digital Business', 'Biomedical Sciences'],
    bio: 'Founder & CEO beautybrand reluvie & hellobuvon | Pharmacodermatology Researcher with expertise in Pharmacy, Aesthetic & Anti Aging Medicine, Digital Business, and Biomedical Sciences',
    featured: true,
    order: 10,
  },
  {
    _type: 'mentor',
    name: 'Arsita Mardiyah, S.Farm',
    slug: { _type: 'slug', current: 'arsita-mardiyah' },
    role: 'Natural Products & Pharmacology',
    rating: 5,
    reviews: '70+',
    cardColor: 'bg-brand-pink',
    borderColor: 'border-white',
    expertise: ['Natural Products', 'Pharmaceutical Cosmetics', 'Regulatory Affairs'],
    bio: 'Menempuh S2 Farmasi Pharmaceutical Cosmetics | Aktif berorganisasi sebagai Sekretaris Badan Mahasiswa Green Dormitory | Aktif sebagai Kader BPOM Jakarta',
    featured: false,
    order: 11,
  },
  {
    _type: 'mentor',
    name: 'apt. Septiyadi, S.Farm., MOS',
    slug: { _type: 'slug', current: 'septiyadi' },
    role: 'Clinical and Community Pharmaceutical',
    rating: 5,
    reviews: '85+',
    cardColor: 'bg-brand-blue',
    borderColor: 'border-white',
    expertise: ['Clinical Pharmacy', 'Herbal Medicine', 'Research Publication'],
    bio: 'Mahasiswa Magister Farmasi Klinis | Publish Jurnal Penelitian "Penggunaan Daun Pencut Kuda sebagai Obat Tradisional"',
    featured: false,
    order: 12,
  },
  {
    _type: 'mentor',
    name: 'apt. Nur Intan, S.Farm',
    slug: { _type: 'slug', current: 'nur-intan' },
    role: 'Clinical and Community Pharmaceutical',
    rating: 5,
    reviews: '65+',
    cardColor: 'bg-brand-yellow',
    borderColor: 'border-white',
    expertise: ['Clinical Pharmacy', 'Community Pharmacy'],
    bio: 'Apoteker profesional dengan dedikasi dalam pelayanan farmasi klinis dan komunitas',
    featured: false,
    order: 13,
  },
  {
    _type: 'mentor',
    name: 'apt. Rania, S.Farm',
    slug: { _type: 'slug', current: 'rania' },
    role: 'Pharmaceutical Cosmetic Sciences',
    rating: 5,
    reviews: '115+',
    cardColor: 'bg-brand-purple',
    borderColor: 'border-white',
    expertise: ['Cosmetic Sciences', 'International Programs'],
    bio: 'Best Bachelors Graduates Faculty of Pharmacy 2023 | ISMAFARSI Summer Student Exchange Program Awardee 2022 | PPA Scholarship Awardee 2022',
    featured: true,
    order: 14,
  },
  {
    _type: 'mentor',
    name: 'Muhammad Ma\'aruf, S.Si., M.Farm',
    slug: { _type: 'slug', current: 'muhammad-maaruf' },
    role: 'Natural Products & Microbiology',
    rating: 5,
    reviews: '130+',
    cardColor: 'bg-brand-teal',
    borderColor: 'border-white',
    expertise: ['Natural Products', 'Microbiology', 'Research & Publication'],
    bio: 'Anggota Peneliti dari Hibah Penelitian Dosen Pemula (PDP) Direktorat Pendidikan Tinggi Vokasi | Wisudawan Terbaik Pertama Program S2 Farmasi Bahan Alam | 10+ Karya Artikel Ilmiah terbit di Jurnal Nasional & Internasional',
    featured: true,
    order: 15,
  },
  {
    _type: 'mentor',
    name: 'apt. Alfia Nayudia Farahnida, S.Farm',
    slug: { _type: 'slug', current: 'alfia-nayudia-farahnida' },
    role: 'Nanotechnology',
    rating: 5,
    reviews: '95+',
    cardColor: 'bg-brand-pink',
    borderColor: 'border-white',
    expertise: ['Nanotechnology', 'PLGA Nanoparticles', 'Research Funding'],
    bio: 'Publication Article in Sinta 2 "Formulation and Characterization of Bacillus subtilis Supernatant loaded PLGA Nanoparticle" | PKM-RE Funding Recipient by Kemendikbud "Virtual Screening Potensial Analgesik & Antiinflamation Ekstract Artemisia Vulgaris L."',
    featured: true,
    order: 16,
  },
  {
    _type: 'mentor',
    name: 'Meity Hartati, S.Farm., M.Farm',
    slug: { _type: 'slug', current: 'meity-hartati' },
    role: 'Pharmacy Molecular Docking',
    rating: 5,
    reviews: '88+',
    cardColor: 'bg-brand-blue',
    borderColor: 'border-white',
    expertise: ['Molecular Docking', 'In Silico Studies', 'Pharmaceutical Production'],
    bio: 'Sertifikasi kegiatan Workshop "In Silico Docking Molekuler" | Sertifikasi PRODAMAT (Produksi & Management Obat) | Sertifikasi Global Forum on Pharmaceutical and Health Sciences (GFPHS)',
    featured: false,
    order: 17,
  },
];

async function seedMentors() {
  try {
    console.log('🗑️  Menghapus data mentor lama...');
    const deleteResult = await client.delete({ query: '*[_type == "mentor"]' });
    console.log(`✅ Berhasil menghapus ${deleteResult.results?.length || 0} mentor lama\n`);
    
    console.log('🚀 Membuat data mentor baru...');
    for (const mentor of mentors) {
      await client.create(mentor);
      console.log(`✅ Berhasil menambahkan: ${mentor.name}`);
    }
    
    console.log(`\n✨ Seeding Selesai! Total ${mentors.length} mentor berhasil ditambahkan.`);
  } catch (err) {
    console.error('❌ Error:', err.message);
    console.error(err);
  }
}

seedMentors();
